name: Update Sponsors

on:
  schedule:
    # Run once a day, at 4pm
    - cron: '0 16 * * *'

env:
  FORCE_COLOR: 2
  NODE: 16

permissions:
  contents: read

jobs:
  fetch:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '${{ env.NODE }}'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Update the README
        run: npm run update-sponsors
        env:
          CHEERIO_SPONSORS_GITHUB_TOKEN: ${{ secrets.CHEERIO_SPONSORS_GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'docs(readme): Update Sponsors'
          title: Update Sponsors
          branch: docs/sponsors
          delete-branch: true
